version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: sudo npm install
      - run: sudo npm run lint #json added 
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: sudo npm i
      - run: sudo npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: sudo npm audit

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test